services:
  wings:
    image: ghcr.io/pterodactyl/wings:v1.13.0
    restart: unless-stopped
    networks:
      - ptero0
    ports:
      - "8080:8080"
      - "2022:2022"
    tty: true
    environment:
      TZ: "America/New_York"
      # For ease of setup, this is going to use root user.
      WINGS_UID: 0
      WINGS_GID: 0
      WINGS_USERNAME: root
      # This is where docker will bind certain parts of container to your actual
      # host OS. These locations will be used later.
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers:/var/lib/docker/containers"
      - "./config:/etc/pterodactyl" # Feel free to change.
      - "/var/lib/pterodactyl:/var/lib/pterodactyl"
      - "/var/log/pterodactyl:/var/log/pterodactyl"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
      - "/run/wings/machine-id:/run/wings/machine-id"

# Use this if running in the same host as the panel.
# networks:
#   ptero0:
#     external: true
